name: ci

on:
  push:
    branches: actions

jobs:
  export-docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Docker build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.focal
          push: true
          tags: localhost:5000/nesi/lambdastack:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/test/lambdastack:latest

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config
      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.7.0
          GOPATH: /tmp/go
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install
      - name: Build Container
        env:
          OUTPUT_CONTAINER: lambdastack.sif
        run: |
          singularity build lambdastack.sif localhost:5000/test/:lambdastack:latest
